"""add topical_fit, contribution_potential, opportunity_score to reddit_opportunities

Revision ID: 051e99bba682
Revises: 831fa39c0a89
Create Date: 2026-08-17 22:59:33.038319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051e99bba682'
down_revision: Union[str, None] = '831fa39c0a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_opportunities', sa.Column('topical_fit_score', sa.Float(), nullable=False))
    op.add_column('reddit_opportunities', sa.Column('contribution_potential_score', sa.Float(), nullable=False))
    op.add_column('reddit_opportunities', sa.Column('opportunity_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_opportunities', 'opportunity_score')
    op.drop_column('reddit_opportunities', 'contribution_potential_score')
    op.drop_column('reddit_opportunities', 'topical_fit_score')
    # ### end Alembic commands ###
