"""add source_fact_ids to content_candidates

Revision ID: 09fbd24be6f0
Revises: 088fdd4efecd
Create Date: 2026-08-17 23:06:45.405991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fbd24be6f0'
down_revision: Union[str, None] = '088fdd4efecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_candidates', sa.Column('source_fact_ids', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_candidates', 'source_fact_ids')
    # ### end Alembic commands ###
