"""initial schema

Revision ID: 2338c140554a
Revises: 
Create Date: 2026-08-17 22:33:36.609240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2338c140554a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('subreddits',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('culture_summary', sa.Text(), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subreddits'))
    )
    op.create_index(op.f('ix_subreddits_name'), 'subreddits', ['name'], unique=True)
    op.create_table('project_facts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('fact_type', sa.Enum('FEATURE', 'CLAIM', 'METRIC', 'USE_CASE', 'AUDIENCE', 'LIMITATION', 'TECHNICAL_DETAIL', 'LINK', name='fact_type'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_facts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_facts'))
    )
    op.create_table('reddit_opportunities',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('subreddit_id', sa.Uuid(), nullable=False),
    sa.Column('reddit_post_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('discussion_score', sa.Float(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZING', 'READY', 'REJECTED', 'USED', 'EXPIRED', name='opportunity_status'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reddit_opportunities_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], name=op.f('fk_reddit_opportunities_subreddit_id_subreddits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reddit_opportunities'))
    )
    op.create_table('source_documents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_source_documents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('project_id', 'content_hash', name=op.f('uq_source_documents_project_id'))
    )
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_table('content_candidates',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'COMMENT', name='content_type'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('source_link', sa.String(length=1000), nullable=True),
    sa.Column('angle', sa.Enum('EDUCATIONAL', 'TECHNICAL', 'PROBLEM_SOLUTION', 'CASE_STUDY', 'OPEN_SOURCE', 'QUESTION', 'DISCUSSION', 'DATA', 'EXPERIMENT', 'ANNOUNCEMENT', name='content_angle'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('PASS', 'REGENERATE', 'BLOCK', 'PENDING', name='validation_status'), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EDITED', 'PUBLISHED', 'FAILED', name='approval_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['reddit_opportunities.id'], name=op.f('fk_content_candidates_opportunity_id_reddit_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_content_candidates_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_candidates'))
    )
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_document_chunks_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_table('validation_results',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('rule_compliance_score', sa.Float(), nullable=False),
    sa.Column('grounding_score', sa.Float(), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('promotion_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['content_candidates.id'], name=op.f('fk_validation_results_candidate_id_content_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_table('document_chunks')
    op.drop_table('content_candidates')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('reddit_opportunities')
    op.drop_table('project_facts')
    op.drop_index(op.f('ix_subreddits_name'), table_name='subreddits')
    op.drop_table('subreddits')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
