"""add chunked_at and facts_extracted_at to source_documents

Revision ID: 831fa39c0a89
Revises: 602bf5976e9e
Create Date: 2026-08-17 22:43:38.657654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831fa39c0a89'
down_revision: Union[str, None] = '602bf5976e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('chunked_at', sa.DateTime(), nullable=True))
    op.add_column('source_documents', sa.Column('facts_extracted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'facts_extracted_at')
    op.drop_column('source_documents', 'chunked_at')
    # ### end Alembic commands ###
